// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-wcHczpKyTRCEZtEc68HKR5t-Ga_Ku2A',
    appId: '1:1020034317708:android:6c26982edc08d2777eeaa9',
    messagingSenderId: '1020034317708',
    projectId: 'doctor-app-57570',
    storageBucket: 'doctor-app-57570.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNw2QLuyyVg4S7vW8_V-452mxQVfGRQq8',
    appId: '1:1020034317708:ios:0710d24cae2af3ce7eeaa9',
    messagingSenderId: '1020034317708',
    projectId: 'doctor-app-57570',
    storageBucket: 'doctor-app-57570.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtl0f_qjWR42etUwAyzyX58Qizu4W3JHE',
    appId: '1:1020034317708:web:513e4ca922a7df437eeaa9',
    messagingSenderId: '1020034317708',
    projectId: 'doctor-app-57570',
    authDomain: 'doctor-app-57570.firebaseapp.com',
    storageBucket: 'doctor-app-57570.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtl0f_qjWR42etUwAyzyX58Qizu4W3JHE',
    appId: '1:1020034317708:web:513e4ca922a7df437eeaa9',
    messagingSenderId: '1020034317708',
    projectId: 'doctor-app-57570',
    authDomain: 'doctor-app-57570.firebaseapp.com',
    storageBucket: 'doctor-app-57570.firebasestorage.app',
  );

}